core_app/urls.py
from django.urls import path

from . import views

app_name = 'core_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topics page
    path('topics/', views.get_topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.get_topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.add_new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.add_new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),


]

knowledge_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('core_app.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),

    # Registration page
    path('register/', views.register, name='register'),

]

core_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Topic(models.Model):
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."

        return self.text

users/models.py
from django.db import models

# Create your models here.

core_app/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title']
        labels = {'title': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

core_app/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


def check_topic_owner(topic, request):
    if topic.owner != request.user:
        raise Http404


def index(request):
    return render(request, 'core_app/index.html')


@login_required
def get_topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}

    return render(request, 'core_app/topics.html', context)


@login_required
def get_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic,
               'entries': entries}

    return render(request, "core_app/topic.html", context)


@login_required
def add_new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('core_app:topics')

    context = {'form': form}
    return render(request, "core_app/new_topic.html", context)


@login_required
def add_new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('core_app:topic', topic_id=topic_id)

    context = {'topic': topic,
               'form': form}
    return render(request, 'core_app/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('core_app:topic', topic_id=topic.id)

    context = {'entry': entry,
               'topic': topic,
               'form': form}
    return render(request, 'core_app/edit_entry.html', context)

users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('core_app:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

core_app/templates/core_app/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Knowledge Log</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a href="{% url 'core_app:index' %}" class="navbar-brand">Knowledge log</a>

        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{% url 'core_app:topics' %}" class="nav-link">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-secondary" type="submit">Log Out</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link">Register</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="nav-link">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
            {% block content %}{% endblock content %}
    </main>
</body>
</html>

core_app/templates/core_app/edit_entry.html
{% extends "core_app/base.html" %}
{% block content %}

    <p><a href="{% url 'core_app:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>
    <form action="{% url 'core_app:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock %}

core_app/templates/core_app/index.html
{% extends "core_app/base.html" %}
{% block page_header %}

    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>

        <p class="lead">Make your own Knowledge Log, and keep a list of the topics
        you're learning about. Whenever your learn something new about a topic,
        make an entry summarizing what you've learned.</p>


        <a href="{% url 'users:register' %}" class="btn btn-lg btn-primary" role="button">Register &raquo;</a>
    </div>

{% endblock page_header %}

core_app/templates/core_app/new_entry.html
{% extends "core_app/base.html" %}
{% block content %}

    <p><a href="{% url 'core_app:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add new entry:</p>
    <form action="{% url 'core_app:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>

{% endblock %}

core_app/templates/core_app/new_topic.html
{% extends "core_app/base.html" %}
{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'core_app:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>
    </form>

{% endblock content %}

core_app/templates/core_app/topic.html
{% extends "core_app/base.html" %}
{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}


{% block content %}

    <p><a href="{% url 'core_app:new_entry' topic.id %}">Add new entry</a></p>
    <ul>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                    {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'core_app:edit_entry' entry.id %}">Edit entry</a>
                </small>
            </h4>
            <div class="card-body">
                    {{ entry.text | linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}
    </ul>

{% endblock content %}

core_app/templates/core_app/topics.html
{% extends "core_app/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

    <ul>
    {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'core_app:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
        {% empty %}
        <li>
            <h3>No topics have been added yet.</h3>
        </li>
    {% endfor %}
    </ul>

    <h3><a href="{% url 'core_app:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}